export const SUPPORTED_ISOCHRONE_TRAVEL_MODES = [
  "drive",
  "truck",
  "bicycle",
  "walk",
  "transit",
];

export const SUPPORTED_ISOCHRONE_TIME_RANGES = ["5", "10", "15"];

export const POI_TYPE_MAP = {
  shops: [
    "Store",
    "anime",
    "antiques",
    "appliances",
    "antiques",
    "baby_goods",
    "bag",
    "beaty",
    "books",
    "boutique",
    "candles",
    "clothes",
    "convenience",
    "cosmetics",
    "craft",
    "department_store",
    "electronics",
    "fabric",
    "florist",
    "grocery",
    "jewelry",
    "kiosk",
    "mall",
    "marketplace",
    "supermarket",
    "variety_store",
    "pharmacy",
  ],
  restaurants: [
    "bakery",
    "bar",
    "beverages",
    "cafe",
    "confectionery",
    "deli",
    "fast_food",
    "food_court",
    "health_food",
    "restaurant",
    "pub",
    "supermarket",
    "tea",
  ],
  entertainment: [
    "art",
    "artist",
    "arts_center",
    "artwork",
    "bandstand",
    "casino",
    "cinema",
    "events_venue",
    "games",
    "library",
    "massage",
    "music",
    "nightclub",
    "nightclub;restaurant",
    "party",
    "social_facility",
    "sports",
    "theatre",
  ],
};
